version: '3.9'

services:
  db:
    image: postgres:14
    container_name: inventory_db
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: app
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    ports:
      - 5432:5432
